// <auto-generated />
using System;
using Asp.Net.Core.Razor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Asp.Net.Core.Razor.Migrations
{
    [DbContext(typeof(PersonalTaxesDBContext))]
    [Migration("20190829133630_Asp.Net.Core.Razor.Models.PersonalTax")]
    partial class AspNetCoreRazorModelsPersonalTax
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Asp.Net.Core.Razor.Models.PersonalTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<decimal>("Tax");

                    b.Property<decimal>("TaxableIncome");

                    b.HasKey("Id");

                    b.ToTable("PersonalTaxes");
                });
#pragma warning restore 612, 618
        }
    }
}
